#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GENERATED_MARKER="# Generated by scripts/bootstrap-worktree.sh"
DEFAULT_WEB_PORT=3000
DEFAULT_API_PORT=4000

usage() {
  cat <<'EOF'
Usage:
  bash scripts/bootstrap-worktree.sh --path <worktree-path> [options]

Options:
  --path <path>          Absolute or relative worktree path to create or prepare.
  --branch <name>        Branch name for a newly created worktree. Defaults to a
                         slug derived from --task-file or the worktree directory.
  --base <ref>           Base ref for a newly created worktree. Defaults to HEAD.
  --existing             Prepare an already existing worktree instead of creating one.
  --task-file <path>     Relative task path to activate inside the prepared worktree.
                         If it points to tasks/todo/, the file is moved to tasks/active/.
  --env-source <path>    Source env file to expose inside the prepared worktree as .env.
                         Defaults to the current repo root .env when it exists.
  --env-mode <mode>      How to expose --env-source inside the worktree: symlink or copy.
                         Defaults to symlink.
  --port-offset <n>      Starting offset from the default web/api ports (3000/4000).
                         If the resulting pair is busy, the script increments until a
                         free pair is found.
  --web-port <n>         Explicit web dev port. Must be provided together with --api-port.
  --api-port <n>         Explicit API port. Must be provided together with --web-port.
  --skip-install         Do not run pnpm install inside the prepared worktree.
  --force                Overwrite generated env files even if they already exist.
  --help                 Show this help message.

Examples:
  pnpm worktree:bootstrap -- \
    --path /tmp/mastersrunners-i0014-020 \
    --task-file tasks/todo/I-0014-020-web-messaging-room-identity-and-hub.md

  pnpm worktree:bootstrap -- \
    --existing \
    --path /tmp/mastersrunners-i0014-020 \
    --env-source /Users/you/project/mastersrunners/.env \
    --port-offset 25
EOF
}

log() {
  printf '[worktree-bootstrap] %s\n' "$*"
}

warn() {
  printf '[worktree-bootstrap] warning: %s\n' "$*" >&2
}

die() {
  printf '[worktree-bootstrap] error: %s\n' "$*" >&2
  exit 1
}

abspath() {
  local input="$1"
  if [[ "$input" = /* ]]; then
    printf '%s\n' "$input"
    return 0
  fi

  printf '%s/%s\n' "$(pwd)" "$input"
}

slugify() {
  local value="$1"
  value="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
  value="$(printf '%s' "$value" | sed -E 's/[^a-z0-9._/-]+/-/g; s#//+#/#g; s/^-+//; s/-+$//')"
  printf '%s' "$value"
}

port_in_use() {
  local port="$1"

  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
    return $?
  fi

  if command -v nc >/dev/null 2>&1; then
    nc -z localhost "$port" >/dev/null 2>&1
    return $?
  fi

  return 1
}

resolve_offset_from_seed() {
  local seed="$1"
  local checksum
  checksum="$(printf '%s' "$seed" | cksum | awk '{print $1}')"
  printf '%s' "$((checksum % 200 + 1))"
}

choose_port_pair() {
  local starting_offset="$1"
  local offset="$starting_offset"
  local web_port
  local api_port

  while true; do
    web_port="$((DEFAULT_WEB_PORT + offset))"
    api_port="$((DEFAULT_API_PORT + offset))"

    if ! port_in_use "$web_port" && ! port_in_use "$api_port"; then
      printf '%s %s %s\n' "$offset" "$web_port" "$api_port"
      return 0
    fi

    offset="$((offset + 1))"
  done
}

assert_safe_to_write() {
  local file_path="$1"
  local force="$2"

  if [ ! -e "$file_path" ]; then
    return 0
  fi

  if grep -qF "$GENERATED_MARKER" "$file_path"; then
    return 0
  fi

  if [ "$force" = "1" ]; then
    return 0
  fi

  die "Refusing to overwrite non-generated file: $file_path (use --force if you really want to replace it)."
}

write_generated_env() {
  local file_path="$1"
  local force="$2"
  shift 2

  assert_safe_to_write "$file_path" "$force"
  mkdir -p "$(dirname "$file_path")"

  local tmp_file
  tmp_file="$(mktemp)"
  {
    printf '%s\n' "$GENERATED_MARKER"
    printf '# Do not hand-edit this file unless you also own the worktree bootstrap contract.\n'
    printf '\n'
    for line in "$@"; do
      printf '%s\n' "$line"
    done
  } >"$tmp_file"
  mv "$tmp_file" "$file_path"
}

activate_task() {
  local worktree_path="$1"
  local task_file="$2"

  if [ -z "$task_file" ]; then
    return 0
  fi

  local source_path="$worktree_path/$task_file"
  [ -f "$source_path" ] || die "Task file not found in prepared worktree: $task_file"

  case "$task_file" in
    tasks/todo/*)
      local target_path="$worktree_path/tasks/active/$(basename "$task_file")"
      [ ! -e "$target_path" ] || die "Target active task already exists: ${target_path#$worktree_path/}"
      mv "$source_path" "$target_path"
      log "Activated task: ${target_path#$worktree_path/}"
      ;;
    tasks/active/*)
      log "Task already active: $task_file"
      ;;
    *)
      die "--task-file must point to tasks/todo/* or tasks/active/*"
      ;;
  esac
}

maybe_install_dependencies() {
  local worktree_path="$1"
  local skip_install="$2"

  if [ "$skip_install" = "1" ]; then
    log "Skipping dependency install."
    return 0
  fi

  if [ -f "$worktree_path/node_modules/.modules.yaml" ]; then
    log "Dependencies already installed."
    return 0
  fi

  log "Installing dependencies with pnpm install --frozen-lockfile"
  (
    cd "$worktree_path"
    pnpm install --frozen-lockfile
  )
}

prepare_workspace_artifacts() {
  local worktree_path="$1"
  local skip_install="$2"
  local needs_types_build=0
  local needs_database_build=0

  if [ ! -f "$worktree_path/packages/types/dist/index.js" ]; then
    needs_types_build=1
  fi

  if [ ! -f "$worktree_path/packages/database/dist/index.js" ]; then
    needs_database_build=1
  fi

  if [ "$needs_types_build" = "0" ] && [ "$needs_database_build" = "0" ]; then
    log "Shared workspace package artifacts already present."
    return 0
  fi

  if [ ! -f "$worktree_path/node_modules/.modules.yaml" ]; then
    if [ "$skip_install" = "1" ]; then
      warn "Skipping shared workspace package build because dependencies are not installed and --skip-install was used."
      return 0
    fi

    die "Dependencies are missing, so shared workspace package artifacts cannot be prepared."
  fi

  log "Building shared workspace packages required by local dev."
  (
    cd "$worktree_path"

    if [ "$needs_types_build" = "1" ]; then
      pnpm --filter @masters/types build
    fi

    if [ "$needs_database_build" = "1" ]; then
      pnpm --filter @masters/database build
    fi
  )
}

prepare_root_env() {
  local worktree_root="$1"
  local env_source="$2"
  local env_mode="$3"
  local force="$4"
  local target_env="$worktree_root/.env"

  if [ -z "$env_source" ]; then
    if [ -f "$ROOT_DIR/.env" ]; then
      env_source="$ROOT_DIR/.env"
    else
      warn "No root env source configured. The bootstrap flow will finish, but runtime commands may still need a repo-root .env."
      return 0
    fi
  fi

  env_source="$(abspath "$env_source")"
  [ -f "$env_source" ] || die "Env source file does not exist: $env_source"

  if [ -L "$target_env" ]; then
    local linked_target
    linked_target="$(readlink "$target_env")"
    if [ "$linked_target" = "$env_source" ] && [ "$env_mode" = "symlink" ]; then
      log "Root env already linked: $target_env -> $env_source"
      return 0
    fi
  fi

  if [ -e "$target_env" ] || [ -L "$target_env" ]; then
    if [ "$force" != "1" ]; then
      die "Refusing to overwrite existing worktree root env: $target_env (use --force to replace it)."
    fi
    rm -f "$target_env"
  fi

  case "$env_mode" in
    symlink)
      ln -s "$env_source" "$target_env"
      ;;
    copy)
      cp "$env_source" "$target_env"
      ;;
    *)
      die "--env-mode must be symlink or copy"
      ;;
  esac
}

existing_mode=0
skip_install=0
force_overwrite=0
worktree_path=""
branch_name=""
base_ref="HEAD"
task_file=""
env_source=""
env_mode="symlink"
port_offset=""
web_port=""
api_port=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --path)
      worktree_path="$2"
      shift 2
      ;;
    --branch)
      branch_name="$2"
      shift 2
      ;;
    --base)
      base_ref="$2"
      shift 2
      ;;
    --task-file)
      task_file="$2"
      shift 2
      ;;
    --env-source)
      env_source="$2"
      shift 2
      ;;
    --env-mode)
      env_mode="$2"
      shift 2
      ;;
    --port-offset)
      port_offset="$2"
      shift 2
      ;;
    --web-port)
      web_port="$2"
      shift 2
      ;;
    --api-port)
      api_port="$2"
      shift 2
      ;;
    --existing)
      existing_mode=1
      shift
      ;;
    --skip-install)
      skip_install=1
      shift
      ;;
    --force)
      force_overwrite=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

[ -n "$worktree_path" ] || die "--path is required"

worktree_path="$(abspath "$worktree_path")"

if [ -n "$port_offset" ] && ! [[ "$port_offset" =~ ^[0-9]+$ ]]; then
  die "--port-offset must be a non-negative integer"
fi

if [ -n "$web_port" ] || [ -n "$api_port" ]; then
  [ -n "$web_port" ] && [ -n "$api_port" ] || die "--web-port and --api-port must be provided together"
  [[ "$web_port" =~ ^[0-9]+$ ]] || die "--web-port must be a non-negative integer"
  [[ "$api_port" =~ ^[0-9]+$ ]] || die "--api-port must be a non-negative integer"
fi

if [ "$existing_mode" = "1" ]; then
  git -C "$worktree_path" rev-parse --show-toplevel >/dev/null 2>&1 || die "Not a git worktree: $worktree_path"
else
  if [ -e "$worktree_path" ]; then
    die "Path already exists. Use --existing to prepare it in place: $worktree_path"
  fi

  mkdir -p "$(dirname "$worktree_path")"

  if [ -z "$branch_name" ]; then
    if [ -n "$task_file" ]; then
      branch_name="task/$(slugify "$(basename "$task_file" .md)")"
    else
      branch_name="task/$(slugify "$(basename "$worktree_path")")"
    fi
  fi

  if git -C "$ROOT_DIR" show-ref --verify --quiet "refs/heads/$branch_name"; then
    log "Creating worktree at $worktree_path from existing branch $branch_name"
    git -C "$ROOT_DIR" worktree add "$worktree_path" "$branch_name"
  else
    log "Creating worktree at $worktree_path from $base_ref on new branch $branch_name"
    git -C "$ROOT_DIR" worktree add "$worktree_path" -b "$branch_name" "$base_ref"
  fi
fi

worktree_root="$(git -C "$worktree_path" rev-parse --show-toplevel)"
branch_name="${branch_name:-$(git -C "$worktree_root" branch --show-current)}"

activate_task "$worktree_root" "$task_file"

if [ -n "$web_port" ]; then
  if port_in_use "$web_port"; then
    warn "Requested web port $web_port is already in use."
  fi
  if port_in_use "$api_port"; then
    warn "Requested API port $api_port is already in use."
  fi
  resolved_offset="$((api_port - DEFAULT_API_PORT))"
else
  if [ -n "$port_offset" ]; then
    requested_offset="$port_offset"
  else
    requested_offset="$(resolve_offset_from_seed "${task_file:-$branch_name:$worktree_root}")"
  fi

  read -r resolved_offset web_port api_port < <(choose_port_pair "$requested_offset")
fi

frontend_url="http://localhost:${web_port}"
api_public_url="http://localhost:${api_port}/api/v1"

write_generated_env "$worktree_root/.env.worktree" "$force_overwrite" \
  "WORKTREE_ROOT=$worktree_root" \
  "WORKTREE_BRANCH=$branch_name" \
  "WORKTREE_TASK_FILE=${task_file:-}" \
  "WORKTREE_PORT_OFFSET=$resolved_offset" \
  "WORKTREE_WEB_PORT=$web_port" \
  "WORKTREE_API_PORT=$api_port" \
  "FRONTEND_URL=$frontend_url" \
  "VITE_API_URL=$api_public_url" \
  "API_PUBLIC_URL=$api_public_url"

write_generated_env "$worktree_root/apps/api/.env.local" "$force_overwrite" \
  "API_PORT=$api_port" \
  "API_PUBLIC_URL=$api_public_url" \
  "FRONTEND_URL=$frontend_url"

write_generated_env "$worktree_root/apps/web/.env.local" "$force_overwrite" \
  "VITE_PORT=$web_port" \
  "VITE_API_URL=$api_public_url"

maybe_install_dependencies "$worktree_root" "$skip_install"
prepare_root_env "$worktree_root" "$env_source" "$env_mode" "$force_overwrite"
prepare_workspace_artifacts "$worktree_root" "$skip_install"

cat <<EOF

[worktree-bootstrap] Ready

Worktree:     $worktree_root
Branch:       $branch_name
Task file:    ${task_file:-"(none)"}
Web port:     $web_port
API port:     $api_port
Frontend URL: $frontend_url
API URL:      $api_public_url

Generated files:
  - $worktree_root/.env
  - $worktree_root/.env.worktree
  - $worktree_root/apps/api/.env.local
  - $worktree_root/apps/web/.env.local

Next commands:
  cd $worktree_root
  pnpm --filter @masters/api dev
  pnpm --filter @masters/web dev

EOF
